### ISSUE TITLE
Training custom monocular video encountered a bug

### ISSUE THREAD

**Issue by SienChen1997** [zju3dv/neuralbody#16]
After i training follow the instruction use my own monocular video,i encountered a problem when visualizing:

> (neuralbody) chensien@Lab-Server:~/neuralbody$ python run.py --type visualize --cfg_file configs/custom_perform.yaml exp_name custom render_views 1
> load model: data/trained_model/if_nerf/custom/latest.pth
> /home/chensien/neuralbody/lib/utils/render_utils.py:12: RuntimeWarning: invalid value encountered in true_divide
>   return x / np.linalg.norm(x)
> [0]
> the results are saved at data/perform/custom
>   0%|                                                                                                                                                         | 0/300 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "run.py", line 126, in <module>
>     globals()['run_' + args.type]()
>   File "run.py", line 99, in run_visualize
>     output = renderer.render(batch)
>   File "lib/networks/renderer/if_clight_renderer_mmsk.py", line 179, in render
>     raw = self.net(sp_input, grid_coords, viewdir, light_pts)
>   File "/home/chensien/anaconda3/envs/neuralbody/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "lib/networks/latent_xyzc.py", line 43, in forward
>     xyzc_features = self.xyzc_net(xyzc, grid_coords)
>   File "/home/chensien/anaconda3/envs/neuralbody/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "lib/networks/latent_xyzc.py", line 125, in forward
>     features = features.view(features.size(0), -1, features.size(4))
> RuntimeError: cannot reshape tensor of 0 elements into shape [1, -1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
>

**Comment by pengsida** [comment]
It is strange.
It seems that you input empty tensors into SparseConvNet, but `xyzc` and `grid_coords` should be the same as those ones during training.

**Comment by pengsida** [comment]
I found the reason.
[This function](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/can_smpl_demo.py#L164) returns rays that intersect with 3D bounding box of human.
[The synthesized cameras](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/can_smpl_demo.py#L27) may be far away from original training cameras.

**Comment by SienChen1997** [comment]
Yes,the `render_w2c` is a nan array,and `ray_o`,`ray_d`,`near`,`far` is empty？How can i solve this problem?

**Comment by pengsida** [comment]
If the target camera is wrong, of course the number of intersected rays is zero.
You need to revise the [gen_path](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/can_smpl_demo.py#L27) function.
I borrow this function from NeRF, which is probably not suitable for monocular videos.
I strongly recommend you to try [this dataset](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/snapshot_demo.py), which rotates SMPL models instead of rotating cameras. But you need to revise some code, including [reading the camera parameters](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/snapshot_demo.py#L23), [reading SMPL parameters](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/snapshot_demo.py#L28), [rotating the SMPL models](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/snapshot_demo.py#L44).
Or I will update a dataset that rotate SMPL models and is suitable for the data format of ZJU-MoCap.

**Comment by pengsida** [comment]
Hi, I have updated the code.
Now you can visualize novel views by rotating SMPL models: `python run.py --type visualize --cfg_file configs/custom_rotate_demo.yaml exp_name <exp_name>`.
An example is as follows:
![image](https://user-images.githubusercontent.com/11582122/115890475-8db63180-a487-11eb-81b1-0dc45049872e.png)

**Comment by SienChen1997** [comment]
Thx for your patience! I update code and run the command, but still raise some RuntimeWarning relate with  intersection of 3d box:
`/home/chensien/neuralbody/lib/utils/if_nerf/if_nerf_data_utils.py:59: RuntimeWarning: divide by zero encountered in true_divide
  d_intersect = (nominator / ray_d[:, None]).reshape(-1, 6)
/home/chensien/neuralbody/lib/utils/if_nerf/if_nerf_data_utils.py:61: RuntimeWarning: invalid value encountered in multiply
`
And the rendered results is all black images.

**Comment by pengsida** [comment]
I updated the code.
