### ISSUE TITLE
qustion about SMPL parameters in dataset

### ISSUE THREAD

**Issue by 1518github** [zju3dv/neuralbody#89]
We know that the SMPL parameters in datasets, such as pose and shape, are usually obtained through HPS methods such as pymaf, Pixie or pare. Thus we want to know how these parameters are obtained in ZJU-MoCap? Are they obtained through an HPS method? We tried to use pymaf to obtain the smpl parameters of the pictures in the dataset, but the results are very different from those provided in the dataset.
In addition , we found that pictures from different perspectives in the same video frame correspond to the same smpl vertices and smpl parameters in ZJU-MoCap. Is this a common SMPL parameter obtained by averaging all perspectives? Or is there another processing method to make the human body from different shooting angles share the same SMPL parameters.

**Comment by pengsida** [comment]
Hi,

The SMPL parameters are estimated from multi-view images using https://github.com/zju3dv/EasyMocap
Because the multi-view images correspond to the human at the same time instant, they have the same SMPL vertices and parameters.

Pymaf, Pixie and Pare are single-view pose estimation methods.  You need to convert their pose format into the format used in the code.

**Comment by 1518github** [comment]
Thanks for your answer! Does _**EasyMocap**_ provide the code that convert single-view pose to multi-view pose, or are there any open source codes in the existing work to support this conversion?
